#!/bin/bash
set -e
set -u

#
# Check if the volume blocks really use the configured block sizes.
#

TestName="$(basename "$(pwd)")"
export TestName

# set other test specific variables
Client=bareos-fd
JobName=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions
"${rscripts}"/cleanup
"${rscripts}"/setup

# Directory to backup.
# This directory will be created by setup_data().
BackupDirectory="${tmp}/data"

# Use a tgz to setup data to be backed up.
# Data will be placed at "${tmp}/data/".
setup_data "$@"

VolumeName=TestVolume001
VolumePath=storage/${VolumeName}
DEFAULT_BLOCK_SIZE=64512
BLS_BLOCKS="${BAREOS_BLS_BINARY} -c ${configs} -k -d 250 -V ${VolumeName} storage"

get_block_and_data_size()
{
    # block 1 and 2 are label blocks.
    # blocks >= 3 are data blocks.
    # Parameter 1 is the block of interest. Default is block 1.
    LINE=${1:-1}
    ${BLS_BLOCKS} | sed -r -n -e "s/^bls .* Exit read_block (read_len=[0-9]+) (block_len=[0-9]*)/\1 \2/p" | sed "${LINE}q;d"

}

get_block_size()
{
    # block 1 and 2 are label blocks.
    # blocks >= 3 are data blocks.
    # Parameter 1 is the block of interest. Default is block 1.
    LINE=${1:-1}
    ${BLS_BLOCKS} | sed -r -n -e "s/^bls .* Exit read_block read_len=([0-9]+) block_len=[0-9]*/\1/p" | sed "${LINE}q;d"
}

get_data_size()
{
    # block 1 and 2 are label blocks.
    # blocks >= 3 are data blocks.
    # Parameter 1 is the block of interest. Default is block 1.
    LINE=${1:-1}
    ${BLS_BLOCKS} | sed -r -n -e "s/^bls .* Exit read_block read_len=[0-9]+ block_len=([0-9]*)/\1/p" | sed "${LINE}q;d"
}



# start the test
start_test

cat <<END_OF_DATA >tmp/bconcmds
@$out tmp/log1.out
label storage=File1 volume=${VolumeName} pool=Full
run job=$JobName level=Full yes
wait
messages
@#
@# now do a restore
@#
@$out ${tmp}/log2.out w
restore client=${Client} where=${tmp}/bareos-restores select
unmark *
mark *
done
yes
wait
messages
quit
END_OF_DATA

# Start the bareos daemons
# and run the bconsole commands from ${tmp}/bconcmds
# Further bconsole commands can be executed by "run_bconsole".
run_bareos

# verify that all are terminated
if ! check_for_zombie_jobs storage=File1 client=${Client}; then
    set_error "zombie jobs"
fi

# stop bareos
stop_bareos

# check log files for common error messages
check_log ${tmp}/log1.out
check_log ${tmp}/log2.out

# check tmp/log1.out and tmp/log2.out for errors
check_two_logs

# check for differences between original files and restored files
check_restore_diff ${BackupDirectory}

# do some manual testing
if [ ! -d ${BackupDirectory} ]; then
    set_error "Directory ${BackupDirectory} does not exists any more."
fi

blocksize_label=$(get_block_size 1)
print_debug "Label block size: $blocksize_label"
if [ $blocksize_label != $DEFAULT_BLOCK_SIZE ]; then
    set_error "Wrong label block size: expected: $DEFAULT_BLOCK_SIZE, got: $blocksize_label"
fi

blocksize_data=$(get_block_size 3)
print_debug "Data block size (block 3): $blocksize_data"
if [ $blocksize_data != $DEFAULT_BLOCK_SIZE ]; then
    set_error "Wrong data block size (block 3): expected: $DEFAULT_BLOCK_SIZE, got: $blocksize_data"
fi

# end tests and check for error codes
end_test
