#!/bin/bash
set -e
set -u
#
# test some ACL restrictions
#
TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions
"${rscripts}"/cleanup
"${rscripts}"/setup

start_test

run_bareos "$@"

# echo "status conf" | bin/bconsole -c etc/bareos/bconsole-acl-none.conf > ${logdir}/acl-none.log
# echo "status conf" | bin/bconsole -c etc/bareos/bconsole-acl-status.conf > ${logdir}/acl-status.log
# echo "status conf" | bin/bconsole -c etc/bareos/bconsole-acl-status-conf.conf > ${logdir}/acl-status-conf.log

# Directory to backup.
# This directory will be created by setup_data "$@"().
BackupDirectory="${tmp}/data"

# Use a tgz to setup data to be backed up.
# Data will be placed at "${tmp}/data/".
setup_data "$@"

start_test

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out /dev/null
messages
@$out $tmp/log1.out
label volume=TestVolume001 storage=File pool=Full
run job=$JobName yes
wait
END_OF_DATA
run_bareos "$@"

#stop_bareos

end_test
